version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
  pre_build:
    commands:
      - cd Backend
      - npm install
  build:
    commands:
      - zip -r lambda.zip .

artifacts:
  files:
    - Backend/lambda.zip
