AWSTemplateFormatVersion: '2010-09-09'
Description: Serverless Todo App Infrastructure

Resources:

  TodoLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: todo-lambda-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  TodoLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: todo-lambda
      Runtime: nodejs20.x
      Handler: index.handler
      Role: !GetAtt TodoLambdaRole.Arn
      Code:
        ZipFile: |
          exports.handler = async () => {
            return {
              statusCode: 200,
              body: "Lambda deployed via CI/CD successfully"
            };
          }
